### ISSUE TITLE
Create UI Class

### ISSUE THREAD

**Issue by JonathanMathBoi** [mucsci-students/2023fa-420-Xterminators#3]
Create a class of functions necessary for the CLI
 
 - [x] Implement function to parse command
 - [x] #2 
 - [x] #16 
 - [x] Implement Show Found Words Function
 - [x] #19
 - [x] #15
 - [x] Implement Help Function
 - [x] Implement Exit Function
 
 - Primary: @mention
 - Secondary: @mention
 - Size: (fib number)
 - Actual Size: (fib number after completion)
 - Actual Time: (in minutes or hours -- after completion)

**Comment by JJSnader** [comment]
All of the action items on here have been done in various commits, so I am going to move this to done. If you feel like it should still be in progress you can move it back.
