### ISSUE TITLE
GUI -- Add Rank Progress Bar

### ISSUE THREAD

**Issue by JonathanMathBoi** [mucsci-students/2023fa-420-Xterminators#43]
Add Rank Progress Bar
 
 - [ ] A progress bar along the top that advances each time the user achieves a new rank.
 - [ ] There should also be a label that says what rank the user is currently.
 - [ ] Add Unit Tests for the rank bar
 
#
 - Primary: @JJSnader 
 - Secondary: @ljvance 
 - Size: M
 - Actual Size: (fib number after completion)
 - Actual Time: (in minutes or hours -- after completion)

**Comment by JJSnader** [comment]
Switching this to be assigned to me since refactoring the CLI turned out to be a much larger task than we anticipated.
