### ISSUE TITLE
Implement Show Puzzle Function

### ISSUE THREAD

**Issue by JonathanMathBoi** [mucsci-students/2023fa-420-Xterminators#7]
Implement function to show the puzzle

- [x] Function should display all seven letter of the puzzle
- The function should have the same output/display each time until the shuffle function is executed

- Primary: @mention
- Secondary: @mention
- Size: (fib number)
- Actual Size: (fib number after completion)
- Actual Time: (in minutes or hours -- after completion)

**Comment by JJSnader** [comment]
This is the same issue as #16, which is finished.
