### ISSUE TITLE
CLI execution

### ISSUE THREAD

**Issue by smschwartz** [mucsci-students/2023fa-420-Xterminators#87]
I'm not sure why your CLI is behaving the way it is in gradle -- it's really distracting to have the extra status bars, etc. in there. What's causing that? (I ran with just gradle rather than gradlew in the hopes of avoiding it, but no luck). It's not a standard gradle thing since no other java groups have had the issue.

**Comment by JJSnader** [comment]
This issue is fixed with a command; the README now has instructions to prevent the status bar from showing up.
